### PR TITLE
Bump version to 1.3.0

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

- https://github.com/mattermost/mattermost-plugin-welcomebot/pull/47
- https://github.com/mattermost/mattermost-plugin-welcomebot/pull/60
- https://github.com/mattermost/mattermost-plugin-welcomebot/pull/69
- https://github.com/mattermost/mattermost-plugin-welcomebot/pull/74
- https://github.com/mattermost/mattermost-plugin-welcomebot/pull/79
- https://github.com/mattermost/mattermost-plugin-welcomebot/pull/82
- https://github.com/mattermost/mattermost-plugin-welcomebot/pull/90
- https://github.com/mattermost/mattermost-plugin-welcomebot/pull/100

### CODE REVIEW

**Review by catalintomai — APPROVED** [review]

**Comment by trilopin** [comment]
@mickmister note that lint is failing in CI

**Comment by DHaussermann** [comment]
I have done some testing on this release and there are issues:
1. The issue is fixed but, I can't make that work as a feature. It will just never welcome guests. Maybe I tried this wrong. @streamer45 maybe you have thoughts on this?
 - Created a guest user and inited them to a team with working welcome message. When the new user logs in for the 1st time they don't get the bot DM even when I add the new field to my config
image

   
2. There's a feature where you can welcome multiple teams that does not work and should be reverted - https://github.com/mattermost/mattermost-plugin-welcomebot/pull/82
3. Theres a feature where we add channel level welcome support to private channels that does not work and should be reverted - https://github.com/mattermost/mattermost-plugin-welcomebot/pull/79 

@mickmister may be able to help on 2. and 3.

**Comment by DHaussermann** [comment]
@streamer45 disregard the comment above. This does work as expected. On some attempts to test I forgot to restart the server. And on the last attempt there was a syntax error (which you can even see in the screen shot 🙃)

**Comment by mickmister** [comment]
Created https://github.com/mattermost/mattermost-plugin-welcomebot/pull/109 to revert:

- https://github.com/mattermost/mattermost-plugin-welcomebot/pull/82
- https://github.com/mattermost/mattermost-plugin-welcomebot/pull/79

**Pull request merged**
