### PR TITLE
Revert #11

### PR DESCRIPTION
**Pull request by cpoile**
Reverting #11

### CODE REVIEW

**Comment by levb** [comment]
@hanzei reverting because of last-moment issues, will try to merge for RC2

**Comment by hanzei** [comment]
@levb Not urgent: What kind of issues did you encounter? I'm just wondering what I broke.

**Comment by cpoile** [comment]
@hanzei Nothing you did -- it was because EnsureBot doesn't have a good upgrade path for the user. We have to figure that out before moving plugins to it. (If there is an existing 'bot' user, EnsureBot will error out saying that username is taken already, because the 'bot' user did not have the 'isbot' flag set on it.)

**Comment by hanzei** [comment]
I see. Thanks for the expiations.

**Comment by hanzei** [comment]
@cpoile Do you take care of merging my branch again or should I submit a PR?

**Comment by hanzei** [comment]
@cpoile Gentle reminder about this

**Comment by cpoile** [comment]
@hanzei Sorry, fell off my github messages list somehow. :) Do you want to just submit a PR and then I'll approve and we can merge right away (Lev already approved).

**Pull request merged**
