### PR TITLE
solves Gh 72 - Welcome bot will not let me add a message to private channels

### PR DESCRIPTION
**Pull request by maisnamrajusingh**
#### Summary
Welcome bot will not let me add a message to private channels
#### Ticket Link
https://github.com/mattermost/mattermost-plugin-welcomebot/issues/72

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Review by jfrerich — APPROVED** [review]
lgtm! Thanks!

**Comment by hanzei** [comment]
Skipping QA review per offline dicussion.

**Comment by hanzei** [comment]
@maisnamrajusingh Does https://github.com/demansoltech/mattermost-plugin-welcomebot/blob/9c84d495fa0440499d74d0fde142c965b03de14c/server/hooks.go#L38-L39 also need to be changed?

**Pull request merged**
